name: matcha

services:
  webapp:
    container_name: matcha_frontend
    build: ./webapp
    env_file: local.env
    ports:
      - "8080:80"
    depends_on:
      - database
      - backend
    develop:
      watch:
        - action: sync
          path: ./webapp/src
          target: /usr/share/nginx/html

  backend:
    container_name: matcha_backend
    build: ./services
    env_file: local.env
    ports:
      - "8081:80"
    networks:
      - back-tier
    depends_on:
      - database
    develop:
      watch:
        - action: sync
          path: ./services/src
          target: /var/www/html
  
  database:
    container_name: matcha_database
    image: mysql
    restart: always
    env_file: local.env
    ports:
      - "3306:3306"
    networks:
      back-tier:
        ipv4_address: 172.16.238.10

    volumes:
      - db_storage:/var/lib/mysql

networks:
  front-tier: {}
  back-tier:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"

volumes:
  db_storage:
